swagger: '2.0'
info:
  version: '1.0.0'
  title: 'LAfrica Mobile Text to Voice API'
host: api.text2voice.duckdns.org
basePath: '/'
consumes:
  - 'application/json'
produces:
  - 'application/json'
paths:
  /auth/login:
    post:
      summary: User authentification
      consumes:
        - application/json
      parameters:
        - in: body
          name: user
          schema:
            type: object
            required:
              - email
              - password
            properties:
              email:
                type: string
                example: francois.dupont@email.com

              password:
                type: string
                example: Password!12345
      responses:
        200:
          description: User authentificated
          schema:
            type: object
            properties:
              id:
                type: integer
                description: The user ID.
              firstname:
                type: string
                description: The user firstname.
              lastname:
                type: string
                description: The user lastname.

        401:
          description: 'Invalid credentials'

        400:
          description: Calling this route with an empty request body (JSON) is a no-op.

  /auth/logout:
    get: 
      summary: User logout
      responses:
        200:
          description: User logged out

  /users/signUp:
    post:
      summary: Registration of a new user
      consumes:
        - application/json
      parameters:
        - in: body
          name: user
          schema:
            type: object
            required:
              - firstname
              - lastname
              - phone_number
              - email
              - password
              - password_confirmation
            properties:
              firstname:
                type: string
                example: François
              lastname:
                type: string
                example: Dupont
              phone_number:
                type: string
                pattern: /^[0-9]?()[0-9](\s|\S)(\d[0-9]{0,})$/
                description: The phone number must be preceded by the phone indicator (i.e. 33 for France, 221 for Senegal etc.) 
                example: "33642519412"
              email:
                type: string
                pattern : ^(([^<>()[\]\\.,;:\s@“]+(\.[^<>()[\]\\.,;:\s@“]+)*)|(“.+“))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$
                example: francois.dupont@email.com
              password:
                type: string
                pattern: /^(?=.{6,}$)(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*\W).*$/
                description: The password must contain one uppercase, one lowercase, one number and one special character and must be at least 6 characters long.
                example: Password!12345
              password_confirmation:
                type: string
                example: Password!12345

      responses:
        200:
          description: User successfully registered
          schema:
            type: object
            $ref: '#/definitions/Sign Up'
            properties:
              id:
                type: integer
                description: The user ID.
              firstname:
                type: string
                description: The user firstname.
              lastname:
                type: string
                description: The user lastname. 
              email:
                type: string
                description: The user email. 
      
        401:
            description: The information provided did not match the requirements

        422:
            description: Email already exists in database

    # $ref: '#/definitions/Registration'
        
  
  /users/{user_id}/campaigns:
    get:
      summary: Get all campaigns for a specific user.
      parameters:
        - in: path
          name: user_id
          type: integer
          required: true
          description: Numeric ID of the user to get.
      produces : 
            - application/json
      responses:
        200:
          description: A list of campaigns
          schema:
            type: array
            items : 
              type: object
              properties:
                id:
                  type: integer
                  description: The campaign ID.
                id_client_user:
                  type: integer
                  description: The user ID.
                name:
                  type: string
                  description: The campaign name.
                text_message:
                  type: string
                  description: The message which has been vocalized.
                vocal_message_file_url:
                  type: string
                  description: Path storage of the audio file.
                date:
                  type: string
                  description: Expected date of campaign broadcasting. 
                sending_status:
                  type: integer
                  description: Status of the campaign (0 if pending, 1 if completed)

        401:
          description: 'Unhautorized. The user is not logged in, or the user ID does not match the user identified by the cookie session or the current user is not allowed to get the user campaigns.'

    post:
      summary: Create a campaign
      consumes:
        - application/json
      parameters:
        - in: body
          name: user
          schema:
            type: object
            required:
              - name
              - text_message
              - vocal_message_file_url
              - date
            properties:
              name:
                type: string
                description: The campaign name.
              text_message:
                type: string
                description: The message which has been vocalized.
              vocal_message_file_url:
                type: string
                description: Path storage of the audio file.
              date:
                type: string
                format : date-time
                description: Expected date of campaign broadcasting (YYYY-MM-DDThh:mm:ssZ)
      responses:
        201:
          description: Campaign created
          schema:
            type: object 
            properties:
              id:
                type: integer
                description: The campaign ID.
              id_client_user:
                type: integer
                description: The user ID.
              name:
                type: string
                description: The campaign name.
              text_message:
                type: string
                description: The message which has been vocalized.
              vocal_message_file_url:
                type: string
                description: Path storage of the audio file.
              date:
                type: string
                description: Expected date of campaign broadcasting. 
              sending_status:
                type: integer
                description: Status of the campaign (0 if pending, 1 if completed)

        401:
          description: 'Unhautorized. The user is not logged in, or the user ID does not match the user identified by the cookie session or the current user.'

        400:
          description: Calling this route with an empty request body (JSON) is a no-op.
    
  /users/{user_id}/campaigns/uploadtext:
    post:
      summary: Upload a .txt or .docx file 
      consumes:
        - multipart/form-data
      parameters:
        - in: path
          name: user_id
          type: integer
          required: true
          description: Numeric ID of the user to get.
        - in: formData
          name: uploaded_text
          required: true
          type: file
          description: The text message to upload. The format supported are .txt and .docx.

      responses:
        200:
          description: Upload success
          schema:
            type: string
            description: The text message uploaded and read by the server.

        401:
          description: 'Unhautorized. The user is not logged in, or the user ID does not match the user identified by the cookie session or the current user.'
          
        404:
          description: 'File upload only support the following filetypes: .txt, .docx'

        500:
          description: 'Something went wrong in reading the file.'

  /users/{user_id}/campaigns/TTS:
    post:
      summary: Vocalization of a text message
      consumes:
        - application/json
      produces:
        - text/plain
      parameters:
        - in: path
          name: user_id
          type: integer
          required: true
          description: Numeric ID of the user to get.
        - in: body
          name: Audio configuration
          schema:
            type: object
            required:
              - message
            properties:
              message:
                type: string
                example: Messsage to vocalize
                description: Message to vocalize
              audioConfig:
                type: object
                properties: 
                  encoding: 
                    type: string
                    description: 'Optionnal. Format of the audio file: MP3 for .mp3, LINEAR16 for .wav. Default is MP3'
                    default: MP3
                    enum: [MP3, LINEAR16] 
                  speakingRate: 
                    type: integer
                    description: Optional. Speaking rate/speed, in the range [0.25, 4.0]. 1.0 is the normal native speed supported by the specific voice. 2.0 is twice as fast, and 0.5 is half as fast. If unset(0.0), defaults to the native 1.0 speed. Any other values < 0.25 or > 4.0 will return an error.
                    default: 1 
                  pitch: 
                    type: integer
                    description: Optional. Speaking pitch, in the range [-20.0, 20.0]. 20 means increase 20 semitones from the original pitch. -20 means decrease 20 semitones from the original pitch.
                    default: 0 
                  volumeGainDb: 
                    type: integer
                    description: Optional. Volume gain (in dB) of the normal native volume supported by the specific voice, in the range [-96.0, 16.0]. If unset, or set to a value of 0.0 (dB), will play at normal native signal amplitude.  Strongly recommend not to exceed +10 (dB) as there's usually no effective increase in loudness for any value greater than that.
                    default: 0 
                  voiceType: 
                    type: string
                    description: Optional. WaveNet is a more realistic voice. When enabled, this option results in an additional billing cost. 
                    default: Standard
                    enum: ['Standard', 'WaveNet']
                  voiceGender: 
                    type: string
                    description: Optional. Configuration of the voice gender. A, C and E are women voices, B and D men voices.
                    default: A
                    enum: ['A', 'B', 'C', 'D', 'E']

      responses:
        200:
          description: Vocalization success. Returns the name of the audio file.
          schema:
            type: string
            description: Name of the audio file.

        401:
          description: 'Unhautorized. The user is not logged in, or the user ID does not match the user identified by the cookie session or the current user.'


  /users/{user_id}/campaigns/audio?audio=file.mp3:
    get:
      summary: Get a stream of an audio file.
      parameters:
        - in: path
          name: user_id
          type: integer
          required: true
          description: Numeric ID of the user to get.
        - in: query
          name: audio
          type: string
          required: true
          description: Audio file name and extension (i.e file.mp3)
      produces : 
            - audio
      responses:
        200:
          description: A stream of the audio file requested.

        401:
          description: 'Unhautorized. The user is not logged in, or the user ID does not match the user identified by the cookie session or the current user is not allowed to get the user campaigns.'

  /users/{user_id}/campaigns/downloadaudio?audio=file.mp3:
    get:
      summary: Download an audio file.
      parameters:
        - in: path
          name: user_id
          type: integer
          required: true
          description: Numeric ID of the user to get.
        - in: query
          name: audio
          type: string
          required: true
          description: Audio file name and extension (i.e file.mp3)
      produces : 
            - audio
      responses:
        200:
          description: Downloads the audio file requested.

        401:
          description: 'Unhautorized. The user is not logged in, or the user ID does not match the user identified by the cookie session or the current user is not allowed to get the user campaigns.'

definitions:
  Sign Up:
    properties:
      firstname:
        type: 'string'
      lastname:
        type: 'string'
      phone_number:
        type: string
        pattern: /^[0-9]?()[0-9](\s|\S)(\d[0-9]{0,})$/
        description: The phone number must be preceded by the phone indicator (i.e. 33 for France, 221 for Senegal etc.) 
      email:
        type: 'string'
        pattern : ^(([^<>()[\]\\.,;:\s@“]+(\.[^<>()[\]\\.,;:\s@“]+)*)|(“.+“))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$
      password:
        type: string
        pattern: /^(?=.{6,}$)(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*\W).*$/
        description: The password must contain one uppercase, one lowercase, one number and one special character and must be at least 6 characters long.
        minLength: 6
      password_confirmation:
        type: string
        minLength: 6
    required:
      - firstname
      - lastname 
      - email
      - phone_number
      - password
      - password_confirmation